server:
  port: 8080
spring:
  application:
    name: back-end
  datasource:
    url: jdbc:mysql://localhost:3306/web_lap_top?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  # config log
logging:
  level:
    org.springframework.security: DEBUG

# api version
api:
  prefix: "api/v1"
